name: Matrix
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node_version: ["1.2.0", "1.2.18", "1.2.16"]
      browser: ["firefox", "chrome", "safari"]
      run: echo ""